import rawIndex from '../../data/tafsir-index/saadi.search.json';

/**
 * ============================================================
 *  Local keyword index over تفسير السعدي.
 *
 *  The tafsir text now lives in Firestore, but the app still has to answer
 *  "which ayah discusses X?" — the keyword, topic and word-meaning fallbacks
 *  scan every explanation today, and a remote key-value store cannot do that.
 *
 *  So the TOKENS ship in the bundle while the TEXT does not: ~2.9 MB replacing
 *  163 MB. Every token is kept (no stopword pruning, no posting caps), which is
 *  what makes the candidate set EXACT rather than approximate — the same ayah
 *  wins as before.
 *
 *  Scoring mirrors chatbotSearch.searchTafseerKeywords() exactly:
 *      +5              per query token found in the ayah text
 *      +2 + 0.5*min(n,5) per query token found in the explanation (n = count)
 *      +12             the full phrase appears in the ayah text
 *      +8              the full phrase appears in the explanation
 *  and a candidate must hit at least half of the query's tokens.
 *
 *  Everything except the +8 explanation-phrase bonus is computable offline,
 *  because the index stores per-ayah occurrence counts. That bonus needs the
 *  text, so `phraseBonusPossible` marks the candidates that could still change
 *  places once their text arrives — see candidatesFor().
 *
 *  Generated by scripts/firebase/buildTafsirAssets.mjs.
 * ============================================================
 */

interface RawSearchIndex {
  v: number;
  source: string;
  /** "surah:ayah,surah:ayah,…" in document order. */
  refs: string;
  /** Normalized ayah text, one line per document. */
  ayahText: string;
  /** "token:delta,delta.count,…" one line per token. */
  tokens: string;
  stats: { docs: number; tokens: number; postings: number };
}

const RAW = rawIndex as RawSearchIndex;

export const SEARCH_INDEX_SOURCE = 'al_saadi' as const;

interface Decoded {
  refs: { surah: number; ayah: number }[];
  ayahText: string[];
  postings: Map<string, { doc: number; count: number }[]>;
}

let decoded: Decoded | null = null;

/**
 * Decoded on first use only. Keyword search is a late fallback in the pipeline,
 * so most questions never pay this cost.
 */
function ensureDecoded(): Decoded {
  if (decoded) return decoded;

  const refs = RAW.refs.split(',').map((entry) => {
    const colon = entry.indexOf(':');
    return {
      surah: Number(entry.slice(0, colon)),
      ayah: Number(entry.slice(colon + 1)),
    };
  });

  const ayahText = RAW.ayahText.split('\n');

  const postings = new Map<string, { doc: number; count: number }[]>();
  for (const line of RAW.tokens.split('\n')) {
    const colon = line.indexOf(':');
    if (colon <= 0) continue;
    const token = line.slice(0, colon);
    const list: { doc: number; count: number }[] = [];
    let cursor = 0;
    for (const part of line.slice(colon + 1).split(',')) {
      const dot = part.indexOf('.');
      const delta = Number(dot === -1 ? part : part.slice(0, dot));
      const count = dot === -1 ? 1 : Number(part.slice(dot + 1));
      cursor += delta;
      list.push({ doc: cursor, count });
    }
    postings.set(token, list);
  }

  decoded = { refs, ayahText, postings };
  return decoded;
}

export interface KeywordCandidate {
  surah: number;
  ayah: number;
  /** Score from everything computable without the explanation text. */
  baseScore: number;
  tokensHit: number;
  /**
   * True when the explanation could still earn the +8 exact-phrase bonus.
   * Callers must fetch these before deciding a winner, or a lower-ranked
   * candidate could be wrongly discarded.
   */
  phraseBonusPossible: boolean;
}

/** The explanation-phrase bonus in chatbotSearch.searchTafseerKeywords(). */
export const EXPLANATION_PHRASE_BONUS = 8;

/**
 * Ranks ayahs for a tokenized query.
 *
 * Returns only candidates that could still win once their text is known:
 * anything whose best possible score (baseScore + the phrase bonus) is below
 * the current best baseScore cannot overtake it, so it is dropped. In practice
 * that leaves a handful of ayahs to fetch rather than the whole corpus.
 */
export function candidatesFor(tokens: string[], limit = 8): KeywordCandidate[] {
  if (tokens.length === 0) return [];
  const idx = ensureDecoded();

  // token -> per-document occurrence count
  const explCounts = new Map<number, Map<string, number>>();
  for (const token of tokens) {
    const list = idx.postings.get(token);
    if (!list) continue;
    for (const { doc, count } of list) {
      let perDoc = explCounts.get(doc);
      if (!perDoc) {
        perDoc = new Map();
        explCounts.set(doc, perDoc);
      }
      perDoc.set(token, count);
    }
  }

  const phrase = tokens.join(' ');
  const required = Math.ceil(tokens.length / 2);

  // Ayah-text hits can make a document a candidate even with no explanation
  // hit, so documents matched only that way must also be considered.
  const considered = new Set<number>(explCounts.keys());
  if (tokens.length > 0) {
    for (let doc = 0; doc < idx.ayahText.length; doc += 1) {
      if (considered.has(doc)) continue;
      const text = idx.ayahText[doc];
      for (const token of tokens) {
        if (text.includes(token)) {
          considered.add(doc);
          break;
        }
      }
    }
  }

  const out: KeywordCandidate[] = [];
  for (const doc of considered) {
    const perDoc = explCounts.get(doc);
    const ayahText = idx.ayahText[doc] ?? '';
    let score = 0;
    let tokensHit = 0;

    for (const token of tokens) {
      const inAyah = ayahText.includes(token);
      const explCount = perDoc?.get(token) ?? 0;
      if (inAyah) score += 5;
      if (explCount > 0) score += 2 + Math.min(explCount, 5) * 0.5;
      if (inAyah || explCount > 0) tokensHit += 1;
    }
    if (tokensHit < required) continue;

    if (tokens.length > 1 && ayahText.includes(phrase)) score += 12;

    const ref = idx.refs[doc];
    if (!ref) continue;
    out.push({
      surah: ref.surah,
      ayah: ref.ayah,
      baseScore: score,
      tokensHit,
      // Only a multi-token query can earn the explanation-phrase bonus, and
      // only when the ayah text did not already earn the larger +12.
      phraseBonusPossible: tokens.length > 1 && !ayahText.includes(phrase),
    });
  }

  out.sort((a, b) => b.baseScore - a.baseScore);
  if (out.length === 0) return out;

  // Provably safe pruning: a candidate can only overtake the leader if its
  // best possible score reaches the leader's known score.
  const bestBase = out[0].baseScore;
  const viable = out.filter(
    (c) => c.baseScore + (c.phraseBonusPossible ? EXPLANATION_PHRASE_BONUS : 0) >= bestBase,
  );
  return viable.slice(0, limit);
}

/** Diagnostics for the offline test harness. */
export function searchIndexStats(): { docs: number; tokens: number; postings: number } {
  return RAW.stats;
}

/** Test seam: force a re-decode. */
export function _resetSearchIndex(): void {
  decoded = null;
}
