import type { TafsirSourceId } from '../../types/data.types';
import saadiManifest from '../../data/tafsir-index/al_saadi.manifest.json';
import ibnKathirManifest from '../../data/tafsir-index/ibn_kathir.manifest.json';
import tabariManifest from '../../data/tafsir-index/al_tabari.manifest.json';

/**
 * ============================================================
 *  ayah -> content-document resolution, entirely offline.
 *
 *  The tafsir TEXT lives in Firestore, but the map from an ayah to the
 *  document that holds its passage ships inside the app (~310 KB for all
 *  three sources). That buys two things:
 *
 *    1. Zero Firestore reads to LOCATE a passage — the app fetches the
 *       content document directly by id.
 *    2. Honest offline behaviour. Without the manifest the app could not
 *       distinguish "this source genuinely has no passage for this ayah"
 *       from "I cannot reach the server", and would have to guess. With it,
 *       a never-online install still answers that question correctly.
 *
 *  Generated by scripts/firebase/buildTafsirAssets.mjs. The encoding is
 *  defined in scripts/firebase/lib/tafsirModel.mjs — keep the two in step.
 *
 *  Encoding, one entry per surah:
 *      "start-end:hash;start-end:hash"
 *  A run covers CONSECUTIVE ayahs that share byte-identical text (Ibn Kathir
 *  and Tabari comment per passage, and the source data repeats that passage on
 *  every ayah it covers). Non-contiguous repeats are simply separate runs
 *  pointing at the same content document, so nothing assumes contiguity.
 * ============================================================
 */

interface RawManifest {
  v: number;
  source: string;
  docs: number;
  contentCount: number;
  runCount: number;
  runs: Record<string, string>;
}

export const MANIFEST_VERSION = 1;

const RAW: Record<TafsirSourceId, RawManifest> = {
  al_saadi: saadiManifest as RawManifest,
  ibn_kathir: ibnKathirManifest as RawManifest,
  al_tabari: tabariManifest as RawManifest,
};

interface Run {
  start: number;
  end: number;
  hash: string;
}

/** Parsed lazily per (source, surah) — a question only ever touches one surah. */
const runCache = new Map<string, Run[]>();

function parseRuns(sourceId: TafsirSourceId, surah: number): Run[] {
  const key = `${sourceId}:${surah}`;
  const cached = runCache.get(key);
  if (cached) return cached;

  const encoded = RAW[sourceId]?.runs?.[String(surah)];
  const runs: Run[] = [];
  if (encoded) {
    for (const part of encoded.split(';')) {
      const colon = part.lastIndexOf(':');
      if (colon <= 0) continue;
      const range = part.slice(0, colon);
      const hash = part.slice(colon + 1);
      const dash = range.indexOf('-');
      const start = Number(dash === -1 ? range : range.slice(0, dash));
      const end = Number(dash === -1 ? range : range.slice(dash + 1));
      if (!Number.isFinite(start) || !Number.isFinite(end) || !hash) continue;
      runs.push({ start, end, hash });
    }
  }
  runCache.set(key, runs);
  return runs;
}

/** Firestore document id for a passage: `{source}__{hash}`. */
export function contentDocId(sourceId: TafsirSourceId, hash: string): string {
  return `${sourceId}__${hash}`;
}

export interface PassageRef {
  source: TafsirSourceId;
  /** Content-document id to fetch. */
  contentId: string;
  /** First ayah of the passage this text covers. */
  ayahStart: number;
  /** Last ayah of the passage this text covers. */
  ayahEnd: number;
}

/**
 * Every distinct passage covering [ayahStart, ayahEnd] in one source, in ayah
 * order and de-duplicated — a range that sits inside a single passage yields
 * ONE reference, not one per ayah. Returns [] when the source has no text for
 * that range, which is a real answer (the "not found" card), not an error.
 */
export function passagesFor(
  sourceId: TafsirSourceId,
  surah: number,
  ayahStart: number | null,
  ayahEnd: number | null,
): PassageRef[] {
  const runs = parseRuns(sourceId, surah);
  if (runs.length === 0) return [];

  // A whole-surah request resolves to the surah's first passage, matching what
  // groupsForRange() did with the local dataset.
  if (ayahStart === null) {
    const first = runs[0];
    return [
      {
        source: sourceId,
        contentId: contentDocId(sourceId, first.hash),
        ayahStart: first.start,
        ayahEnd: first.end,
      },
    ];
  }

  const lo = ayahStart;
  const hi = ayahEnd ?? ayahStart;
  const seen = new Set<string>();
  const out: PassageRef[] = [];

  for (const run of runs) {
    if (run.start > hi || run.end < lo) continue;
    const id = contentDocId(sourceId, run.hash);
    if (seen.has(id)) continue;
    seen.add(id);
    out.push({ source: sourceId, contentId: id, ayahStart: run.start, ayahEnd: run.end });
  }
  return out;
}

/** True when the source has any passage covering the range — offline-safe. */
export function hasPassage(
  sourceId: TafsirSourceId,
  surah: number,
  ayahStart: number | null,
  ayahEnd: number | null,
): boolean {
  return passagesFor(sourceId, surah, ayahStart, ayahEnd).length > 0;
}

/** Diagnostic counts, used by the offline test harness. */
export function manifestStats(sourceId: TafsirSourceId): {
  docs: number;
  contentCount: number;
  runCount: number;
} {
  const m = RAW[sourceId];
  return { docs: m?.docs ?? 0, contentCount: m?.contentCount ?? 0, runCount: m?.runCount ?? 0 };
}

/** Test seam: drop parsed runs so a run can start from a clean slate. */
export function _resetManifestCache(): void {
  runCache.clear();
}
