import type { AppLanguage } from '../types/chat.types';

/** All UI copy in both languages — the app is fully bilingual. */
export const STRINGS = {
  ar: {
    appTitle: 'بصيرة',
    appSubtitle: 'مساعد يجيب من نص التفسير فقط — بلا ذكاء اصطناعي توليدي',
    welcome:
      'السلام عليكم، اسألني من البيانات المتوفرة لدي وسأجيبك مع المرجع إن وجد.',
    welcomeHint:
      'اسأل عن تفسير سورة أو آية، مثل: «تفسير سورة الفاتحة» أو «البقرة آية ١٥٣».',
    inputPlaceholder: 'اكتب سؤالك هنا…',
    send: 'إرسال',
    clearChat: 'مسح المحادثة',
    suggestedTitle: 'أسئلة مقترحة',
    typing: 'يبحث في التفسير…',
    dataLoading: 'جارٍ تحميل بيانات التفسير…',
    dataError: 'تعذر تحميل بيانات التفسير. أعد فتح التطبيق للمحاولة مجددًا.',
    rateLimit: 'رويدًا… انتظر لحظة قبل إرسال سؤال آخر.',
    referenceLabel: 'المرجع',
    quranLabel: 'قرآن كريم',
    bookLabel: 'كتاب',
    surahLabel: 'سورة',
    ayahLabel: 'الآية',
    readMore: 'اقرأ المزيد',
    readLess: 'إظهار أقل',
    copy: 'نسخ',
    copied: 'تم النسخ ✓',
    footer:
      'يجيب هذا المساعد من بيانات محلية فقط (تفسير السعدي) ولا يولّد محتوى دينيًا من تلقاء نفسه، وليس بديلًا عن سؤال أهل العلم.',
    langToggle: 'EN',
    skipStreaming: 'انقر لإظهار الإجابة كاملة',
    fatwaNotice:
      'هذا السؤال يحتاج إلى الرجوع لأهل العلم، ويمكنني عرض الآيات والتفاسير المرتبطة فقط.',
    homeTagline: 'مساعد يجيب من نص التفسير فقط',
    startChat: 'ابدأ المحادثة',
    featureTafseer: 'إجابات من التفسير',
    featureLocalSearch: 'بحث محلي',
    featureNoAI: 'بدون ذكاء اصطناعي خارجي',
    featurePrivacy: 'خصوصية أعلى',
    navHome: 'الرئيسية',
    navChat: 'المحادثة',
    navAbout: 'عن التطبيق',
    navPrivacy: 'الخصوصية',
    navSecurity: 'الأمان',
    aboutTitle: 'عن التطبيق',
    aboutBody:
      'بصيرة مساعد محلي يجيب حصريًا من نص تفسير السعدي المخزَّن داخل التطبيق. لا يتصل بأي خدمة ذكاء اصطناعي خارجية، ولا يولّد تفسيرًا أو آيات من تلقاء نفسه؛ كل إجابة إما نقل حرفي من البيانات المحلية أو رسالة واضحة تفيد بعدم وجود نتيجة.',
    privacyTitle: 'الخصوصية',
    privacyBody:
      'في هذا الإصدار، تبقى أسئلتك ومحادثتك على جهازك فقط ولا تُرسَل إلى أي خادم. لا يتطلب التطبيق تسجيل دخول أو إنشاء حساب. يمكنك مسح سجل المحادثة في أي وقت من داخل شاشة المحادثة.',
    securityTitle: 'الأمان',
    securityBody:
      'يُنقّي التطبيق كل نص يُدخله المستخدم من الأحرف غير المرئية وأحرف التحكم قبل معالجته. جميع الإجابات تُبنى حصريًا من بيانات محلية مخزَّنة داخل التطبيق دون أي استدعاء لواجهات ذكاء اصطناعي خارجية، ولا يُعرض أي محتوى HTML غير آمن.',
    charCount: (n: number, max: number) => `${n}/${max}`,
    formatTime: (ts: number) =>
      new Date(ts).toLocaleTimeString('ar', {
        hour: '2-digit',
        minute: '2-digit',
      }),
    // Western digits with comma grouping — clearer at small sizes and
    // consistent with the ayah numbers shown elsewhere in the UI.
    formatNumber: (n: number) => n.toLocaleString('en-US'),
    suggestions: [
      'تفسير سورة الفاتحة',
      'كم مرة ذكرت كلمة الله في القرآن؟',
      'تفسير سورة البقرة آية 255',
      'ما معنى الصبر في الإسلام؟',
    ],
    suggestionCategories: [
      {
        key: 'tafsir',
        label: 'تفسير',
        questions: ['اشرح آية الكرسي', 'هل هذا السؤال يحتاج إلى أهل العلم؟'],
      },
      {
        key: 'meaning',
        label: 'معاني كلمات',
        questions: ['ما معنى الصمد؟', 'ما معنى الصبر في الإسلام؟'],
      },
      {
        key: 'stats',
        label: 'إحصائيات',
        questions: ['كم مرة ذكرت كلمة الله؟', 'كم عدد آيات سورة البقرة؟'],
      },
      {
        key: 'topics',
        label: 'موضوعات',
        questions: ['آيات عن الصبر', 'ماذا يقول القرآن عن التوبة؟'],
      },
      {
        key: 'search',
        label: 'بحث في القرآن',
        questions: ['أين وردت كلمة النور؟', 'في أي سورة وردت عبارة اهدنا الصراط المستقيم؟'],
      },
    ],

    // ---- Quran reading section ----------------------------------------
    navQuran: 'القرآن',
    quranNavCard: 'قراءة القرآن',
    quranHomeTitle: 'القرآن الكريم',
    quranHomeSubtitle: 'نص عثماني كامل، محفوظ محليًا على جهازك',
    quranDataError:
      'تعذّر التحقق من اكتمال نص القرآن الكريم داخل التطبيق. بعض السور أو الآيات قد لا تظهر بشكل صحيح.',
    continueReading: 'متابعة القراءة',
    continueReadingFrom: (surah: string, ayah: number) => `${surah} — الآية ${ayah}`,
    browseSurahs: 'فهرس السور',
    quranSearch: 'البحث في القرآن',
    bookmarks: 'المفضلة',
    surahListTitle: 'فهرس السور',
    surahSearchPlaceholder: 'ابحث باسم السورة…',
    ayahCountSuffix: (n: number) => `${n} آية`,
    meccan: 'مكية',
    medinan: 'مدنية',
    juzLabel: 'الجزء',
    pageLabel: 'الصفحة',
    quranSearchPlaceholder: 'اكتب كلمة أو عبارة من القرآن…',
    quranSearchEmpty: 'اكتب كلمتين على الأقل للبحث في نص القرآن الكريم.',
    quranSearchNoResults: 'لم يتم العثور على نتائج مطابقة في نص القرآن الكريم.',
    quranSearchResultsCount: (n: number) => `${n} نتيجة`,
    bookmarksTitle: 'الآيات المفضلة',
    bookmarksEmpty: 'لا توجد آيات محفوظة بعد. اضغط أيقونة النجمة بجانب أي آية لحفظها هنا.',
    removeBookmark: 'إزالة من المفضلة',
    addBookmark: 'إضافة إلى المفضلة',
    fontSizeLabel: 'حجم الخط',
    increaseFontSize: 'تكبير الخط',
    decreaseFontSize: 'تصغير الخط',
    backToSurahs: 'فهرس السور',
    openSurah: 'فتح السورة',
    startFromBeginning: 'البدء من الفاتحة',
    quranDataInvalidBadge: (count: number, expected: number) =>
      `تحذير: عدد الآيات المحمّلة ${count} من أصل ${expected} متوقعة.`,

    // ---- Mushaf (604-page) reader ---------------------------------------
    mushafMode: 'الوضع المصحفي',
    surahMode: 'وضع السور',
    mushafModeSubtitle: 'صفحات المصحف الشريف كما تُطبع',
    mushafDataMissing: 'بيانات تخطيط صفحات المصحف غير مضافة بعد.',
    mushafDataPartialNote: (loaded: number, expected: number) =>
      `تمت إضافة تخطيط ${loaded} من أصل ${expected} صفحة حتى الآن.`,
    pageOf: (page: number, total: number) => `صفحة ${page} من ${total}`,
    jumpToPage: 'الانتقال إلى صفحة',
    jumpToPagePlaceholder: 'رقم الصفحة (١–٦٠٤)',
    go: 'انتقال',
    previousPage: 'الصفحة السابقة',
    nextPage: 'الصفحة التالية',
    bookmarkPage: 'حفظ الصفحة في المفضلة',
    pageBookmarked: 'الصفحة محفوظة في المفضلة',
    invalidPageNumber: (max: number) => `أدخل رقم صفحة بين ١ و ${max}.`,
    back: 'رجوع',
    jumpAction: 'الانتقال',
    jumpTitle: 'الانتقال السريع',
    jumpTabPage: 'الصفحة',
    jumpTabSurah: 'السورة',
    jumpTabJuz: 'الجزء',
    searchSurahPlaceholder: 'ابحث عن سورة…',
    close: 'إغلاق',
  },
  en: {
    appTitle: 'Baseera',
    appSubtitle: 'An assistant that answers only from the tafsir text — no generative AI',
    welcome:
      'Ask me anything from the provided data, and I will answer with references when available.',
    welcomeHint:
      'Ask about the tafsir of a surah or ayah, e.g. "Tafsir of Surah Al-Fatihah" or "Al-Baqarah ayah 153".',
    inputPlaceholder: 'Type your question here…',
    send: 'Send',
    clearChat: 'Clear chat',
    suggestedTitle: 'Suggested questions',
    typing: 'Searching the tafsir…',
    dataLoading: 'Loading tafsir data…',
    dataError: 'Could not load the tafsir data. Please reopen the app to try again.',
    rateLimit: 'Easy… wait a moment before sending another question.',
    referenceLabel: 'Reference',
    quranLabel: 'Quran',
    bookLabel: 'Book',
    surahLabel: 'Surah',
    ayahLabel: 'Ayah',
    readMore: 'Read more',
    readLess: 'Show less',
    copy: 'Copy',
    copied: 'Copied ✓',
    footer:
      'This assistant answers only from local data (Tafseer As-Saʿdi). It never generates religious content on its own and is not a substitute for asking scholars.',
    langToggle: 'ع',
    skipStreaming: 'Click to show the full answer',
    fatwaNotice:
      'This question needs to be referred to people of knowledge. I can only show related verses and their tafsir.',
    homeTagline: 'An assistant that answers only from the tafsir text',
    startChat: 'Start chatting',
    featureTafseer: 'Answers from tafsir',
    featureLocalSearch: 'Local search',
    featureNoAI: 'No external AI',
    featurePrivacy: 'Higher privacy',
    navHome: 'Home',
    navChat: 'Chat',
    navAbout: 'About',
    navPrivacy: 'Privacy',
    navSecurity: 'Security',
    aboutTitle: 'About this app',
    aboutBody:
      'Baseera is a local assistant that answers exclusively from the Tafseer As-Saʿdi text bundled with the app. It never connects to any external AI service and never generates tafsir or verses on its own; every answer is either a literal excerpt from local data or a clear message stating no result was found.',
    privacyTitle: 'Privacy',
    privacyBody:
      'In this version, your questions and chat stay on your device only and are never sent to a server. No sign-in or account is required. You can clear your chat history at any time from the chat screen.',
    securityTitle: 'Security',
    securityBody:
      'The app sanitizes all user input, stripping invisible and control characters before processing. Every answer is built exclusively from local data bundled with the app, with no calls to external AI APIs, and no unsafe HTML is ever rendered.',
    charCount: (n: number, max: number) => `${n}/${max}`,
    formatTime: (ts: number) =>
      new Date(ts).toLocaleTimeString('en-US', {
        hour: '2-digit',
        minute: '2-digit',
      }),
    formatNumber: (n: number) => n.toLocaleString('en-US'),
    suggestions: [
      'Tafsir of Surah Al-Fatihah',
      'How many times is «الله» mentioned?',
      'Surah Al-Baqarah ayah 255',
      'What is patience in Islam?',
    ],
    suggestionCategories: [
      {
        key: 'tafsir',
        label: 'Tafsir',
        questions: ['Explain Ayat al-Kursi', 'Does this question need a scholar?'],
      },
      {
        key: 'meaning',
        label: 'Word meanings',
        questions: ['What does "As-Samad" mean?', 'What is patience in Islam?'],
      },
      {
        key: 'stats',
        label: 'Statistics',
        questions: ['How many times is «الله» mentioned?', 'How many ayahs does Surah Al-Baqarah have?'],
      },
      {
        key: 'topics',
        label: 'Topics',
        questions: ['Verses about patience', 'What does the Quran say about repentance?'],
      },
      {
        key: 'search',
        label: 'Search the Quran',
        questions: ['Where is the word «النور» mentioned?', 'Which surah contains "Guide us to the straight path"?'],
      },
    ],

    // ---- Quran reading section ----------------------------------------
    navQuran: 'Quran',
    quranNavCard: 'Read the Quran',
    quranHomeTitle: 'The Holy Quran',
    quranHomeSubtitle: 'Full Uthmani text, stored locally on your device',
    quranDataError:
      'Could not verify that the Quran text bundled with the app is complete. Some surahs or ayahs may not display correctly.',
    continueReading: 'Continue reading',
    continueReadingFrom: (surah: string, ayah: number) => `${surah} — Ayah ${ayah}`,
    browseSurahs: 'Surah index',
    quranSearch: 'Search the Quran',
    bookmarks: 'Bookmarks',
    surahListTitle: 'Surah index',
    surahSearchPlaceholder: 'Search by surah name…',
    ayahCountSuffix: (n: number) => `${n} ayahs`,
    meccan: 'Meccan',
    medinan: 'Medinan',
    juzLabel: 'Juz',
    pageLabel: 'Page',
    quranSearchPlaceholder: 'Type a word or phrase from the Quran…',
    quranSearchEmpty: 'Type at least two letters to search the Quran text.',
    quranSearchNoResults: 'No matching results were found in the Quran text.',
    quranSearchResultsCount: (n: number) => `${n} result(s)`,
    bookmarksTitle: 'Bookmarked ayahs',
    bookmarksEmpty: 'No saved ayahs yet. Tap the star icon next to any ayah to save it here.',
    removeBookmark: 'Remove bookmark',
    addBookmark: 'Add bookmark',
    fontSizeLabel: 'Font size',
    increaseFontSize: 'Increase font size',
    decreaseFontSize: 'Decrease font size',
    backToSurahs: 'Surah index',
    openSurah: 'Open surah',
    startFromBeginning: 'Start from Al-Fatihah',
    quranDataInvalidBadge: (count: number, expected: number) =>
      `Warning: ${count} of the expected ${expected} ayahs were loaded.`,

    // ---- Mushaf (604-page) reader ---------------------------------------
    mushafMode: 'Mushaf mode',
    surahMode: 'Surah mode',
    mushafModeSubtitle: 'Real printed Mushaf pages',
    mushafDataMissing: 'Mushaf page layout data has not been added yet.',
    mushafDataPartialNote: (loaded: number, expected: number) =>
      `${loaded} of ${expected} pages have layout data so far.`,
    pageOf: (page: number, total: number) => `Page ${page} of ${total}`,
    jumpToPage: 'Jump to page',
    jumpToPagePlaceholder: 'Page number (1–604)',
    go: 'Go',
    previousPage: 'Previous page',
    nextPage: 'Next page',
    bookmarkPage: 'Bookmark this page',
    pageBookmarked: 'Page bookmarked',
    invalidPageNumber: (max: number) => `Enter a page number between 1 and ${max}.`,
    back: 'Back',
    jumpAction: 'Go to',
    jumpTitle: 'Quick navigation',
    jumpTabPage: 'Page',
    jumpTabSurah: 'Surah',
    jumpTabJuz: 'Juz',
    searchSurahPlaceholder: 'Search surah…',
    close: 'Close',
  },
} as const;

export type UIStrings = (typeof STRINGS)[AppLanguage];
